[package]
name = "serde_macros"
version = "0.3.2"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Macros to auto-generate implementations for the serde framework"
repository = "https://github.com/erickt/rust-serde"

[lib]
name = "serde_macros"
plugin = true

[dependencies]
quasi_macros = {git = "https://github.com/kbknapp/rust-quasi_macros"}

[dependencies.aster]
git = "https://github.com/kbknapp/rust-aster"

[dependencies.quasi]
git = "https://github.com/kbknapp/rust-quasi"
